POST http://localhost:5093/breakfasts
Content-Type: application/json

{
  "name": "Vegan Sunshine",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": ["Oatmeal", "Avocado Toast", "Omelette", "Salad"],
  "Sweet": ["Cookie"]
}

###
GET http://localhost:5093/breakfasts/3462f1a3-0089-42c9-82fe-44783f8b0e86